baseURL = "/"
languageCode = "en-us"
title = "sct"
theme = "goals-theme"

[taxonomies]
goal = "goals"

[Params]
editNetlifyCmsUrl = "/edit/#/collections"
# featured_taxonomies = ["tags", "cities"]

[menu]
[[menu.main]]
name = "Sct"
url = "/"
weight = -120

[[menu.main]]
name = "Goals"
url = "/goals/"
weight = -110

[[menu.main]]
name = "Actions"
url = "/actions/"
weight = -100

[[menu.main]]
name = "Notes"
url = "/notes"
weight = -90

[[menu.main]]
name = "(edit)"
url = "/edit/"
weight = -80

[[menu.main]]
name = "(chat)"
url = "https://matrix.to/#/#sctlib:matrix.org"
weight = -70